"""Ajout du champ last_login à User

Revision ID: 303a2a118157
Revises: 2487ff0ec7f1
Create Date: 2025-08-02 10:35:03.013645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303a2a118157'
down_revision = '2487ff0ec7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
