"""Ajout du modèle ReturnRecord pour gestion des retours

Revision ID: 952f0658a4fb
Revises: 003fdefa03b9
Create Date: 2025-07-25 13:58:49.220800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952f0658a4fb'
down_revision = '003fdefa03b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return_record')
    # ### end Alembic commands ###
